"""Núcleo de cálculo de MOORA (funciones puras, sin dependencias de la interfaz)."""

from .moora import (
    RATIO_SYSTEM,
    REFERENCE_POINT,
    MooraResult,
    RankingComparison,
    ZeroNormColumnError,
    column_norms,
    compare_rankings,
    rank,
    ratio_system,
    reference_deviations,
    reference_point,
    reference_point_scores,
    solve,
    spearman_label,
    spearman_rho,
    vector_normalize,
    weighted_normalized,
)
from .sensitivity import SensitivityResult, redistribute_weights, sensitivity_analysis, stability_table
from .weights import (
    EntropyResult,
    entropy_analysis,
    entropy_weights,
    equal_weights,
    normalize_weights,
    weights_sum_to_one,
)

__all__ = [
    "RATIO_SYSTEM",
    "REFERENCE_POINT",
    "EntropyResult",
    "MooraResult",
    "RankingComparison",
    "SensitivityResult",
    "ZeroNormColumnError",
    "column_norms",
    "compare_rankings",
    "entropy_analysis",
    "entropy_weights",
    "equal_weights",
    "normalize_weights",
    "rank",
    "ratio_system",
    "redistribute_weights",
    "reference_deviations",
    "reference_point",
    "reference_point_scores",
    "sensitivity_analysis",
    "solve",
    "spearman_label",
    "spearman_rho",
    "stability_table",
    "vector_normalize",
    "weighted_normalized",
    "weights_sum_to_one",
]
